export const Colors = {
  SOFT_PINK: "#C09D9D",
  PRETTY_CREAM: "#CDC8C2",
  PRETTY_CREAM_TRANSPARENT: "#CDC8C2F0",
  UGLY_CREAM: "#F7EFE2",
  NEON_YELLOW:"#D2E500",
  NEON_YELLOW_TRANSPARENT:"#D2E500BF",
  BLACKISH:"#1A2032",
  WHITE_SMUDGE: "#ffffffAE",

}